### ISSUE TITLE
Building section todo's

### ISSUE THREAD

**Issue by IgSit** [IgSit/city-builder-FoE#1]
- [x]  w panelu listy budynków `(BuildingListSection)` powinno wyświetlać się 6 budynków - należy zrobić min 6 budynków i ręcznie ustawić Pointy w `calc_position` - dla większej ilości budynków pod spodem powinny być buttony lewo/prawo, dzięki którym przeskakujemy o kolejne 6 budynków na liście - do rozważenia `i % 6 w calc_position` i trzymanie w tej klasie `startIdx i endIdx` które mają obecną stronę listy, a buttony prawo/lewo zmieniają slice tablicy budynków (rysujemy tylko budynki `buildings[startIdx:endIdx],` dzięki czemu zmieniamy budynki na liście - **całość kodu w BuildingListSection**
- [ ] - w tym samym panelu, najlepiej pod buttonami prawo/lewo, podział na kategorie budynków (patrz FoE), dzięki czemu zawężamy filtrowanie za pomocą tych przycisków, kod też tylko w tej sekcji
- [ ] należy zablokować **event propagation** w panelu, na chwilę obecną kliknięcie panelu to też kliknięcie mapy pod nim
- [x] dodanie w `ControlsGui` w lewym górnym rogu ekranu info o zasobach (hajs, młotki, ludzie)
- [x] dodanie początkowych wartości tych zasobów i kontrola oraz update tych zasobów przy budowaniu i sprzedaży
- [x] uzupełnienie funkcji move/sell w `ControlsGui`: w przypadku move korzystamy z kodu w `BuilderGui`, w przypadku sell sprawa jest prosta :)
- [x] kliknięcie na budynek LPM - na razie wystarczy print, jakim budynkiem i gdzie jestem, docelowo nowa `Section` tak jak `BuildingListSection`
